baseUrl: https://schoenlaub.dev
title: Manuel Schönlaub
enableRobotsTXT: true
pluralizeListTitles: false
theme: featherlite

taxonomies:
  tag: tags
  author: authors
  serie: series

languages:
  en:
    languageName: English
    languageCode: "en-US"

paginate: 3

build:
  writeStats: true
  cachebusters:
    - source: "assets/watching/hugo_stats\\.json"
      target: "styles\\.css"
    - source: "(postcss|tailwind)\\.config\\.js"
      target: "css"
    - source: "assets/.*\\.(js|ts|jsx|tsx)"
      target: "js"
    - source: "assets/.*\\.(.*)$"
      target: "$1"

sectionPagesMenu: "main"

menu:
  social:
    - identifier: github
      name: github
      url: "https://github.com/mschoenlaub"
      weight: 1
    - identifier: linkedin
      name: linkedin
      url: "https://www.linkedin.com/mschoenlaub"
      weight: 3
    - identifier: rss
      name: rss
      weight: 5

markup:
  highlight:
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: false
    noHl: false
    style: dracula
    tabWidth: 2

params:
  authors:
    - mschoenlaub
  themeColor: "#000000"
  titleImage: img/avatar.jpg
  headerTitle: mschoenlaub@blog:~$
  indieweb:
    authorizationEndpoint: "https://indieauth.com/auth"
    tokenEndpoint: "https://tokens.indieauth.com/token"
  webmention:
    webmentionUrl: "https://webmention.io"
    webmentionEndpoint: "/schoenlaub.dev/webmention"
    webmentionPingbackEndpoint: "/schoenlaub.dev/xmlrpc"

permalinks:
  posts: "/:year/:month/:slug/"
  blog: "/:year/:month/:slug/"
  note: "/:year/:month/:day/:filename/"
  page: "/:slug/"

module:
  mounts:
    - source: "assets"
      target: "assets"
    - source: "./node_modules/feather-icons/dist/icons"
      target: "assets/icons/feather"
    - source: "./node_modules/@fontsource"
      target: "assets/css"
    - source: "./node_modules/@fontsource/fira-code/files"
      target: "static/css/files"
    - source: "./node_modules/@fontsource/fira-sans/files"
      target: "static/css/files"
    - source: "./node_modules/@fontsource/merriweather/files"
      target: "static/css/files"
    - source: "hugo_stats.json"
      target: "assets/watching/hugo_stats.json"
