version: 2.1

commands:
  hugo:
    description: Compiles hugo page
    parameters:
      minify:
        type: boolean
        default: false
    steps:
      - run: git submodule sync && git submodule update --init
      - run: "hugo -v <<# parameters.minify >> --minify<</ parameters.minify >>"

executors:
  builder:
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
      HUGO_ENV: production
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
  publisher:
    docker:
      - image: sergeyfast/alpine-rsync
    working_directory: ~/hugo

jobs:
  build-minified:
    executor: builder
    environment:
      HUGO_PUBLISHDIR: minified
    steps:
      - run: sudo apt update && sudo apt install git
      - checkout
      - run: git submodule sync && git submodule update --init
      - hugo:
          minify: true
      - persist_to_workspace:
          root: ./
          paths: minified
  build:
    executor: builder
    environment:
      HUGO_PUBLISHDIR: build
    steps:
      - run: sudo apt update && sudo apt install git
      - checkout
      - run: git submodule sync && git submodule update --init
      - hugo:
          minify: false
      - persist_to_workspace:
          root: ./
          paths: build
  test:
    executor: builder
    steps:
      - attach_workspace:
          at: /tmp
      - run: htmlproofer /tmp/build --allow-hash-href --check-html --empty-alt-ignore --disable-external || true
  deploy:
    executor: publisher
    steps:
      - attach_workspace:
          at: /tmp
      - run: |
          if [ "${CIRCLE_BRANCH}" = "master" ]; then
            echo -e "Starting to deploy to Github Pages\n"
            git config --global user.email "builds@circleci.com"
            git config --global user.name "CircleCI"
            #using token clone gh-pages branch
            git clone --quiet --branch=$CIRCLE_BRANCH https://${GH_TOKEN}@github.com/${TARGET_REPO} ./repo > /dev/null
            #go into directory and copy data we're interested in to that directory
            cd repo
            echo "rsync built code with checked out code..."
            rsync -r --exclude=.git --delete /tmp/minified/ ./
            #add, commit and push files
            echo "add files to git..."
            git add -f .
            echo "www.schoenlaub.info" > ./CNAME
            echo "commit files to git repository..."
            if git commit -m "CircleCI build $CIRCLE_BUILD_NUM pushed to Github Pages" ; then
              echo "git push files with force..."
              git push -fq origin master > /dev/null
              echo -e "Deploy completed\n"
            else
              echo "Content not changed, nothing to deploy"
            fi
          else
            echo "Not master branch, dry run only"
          fi

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - build-minified
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build-minified