name: "Publish GitHub Pages artifact"
description: "A composite action that uploads your static assets to a page"
author: "Manuel Schönlaub"
inputs:
  name:
    description: 'Artifact name'
    required: false
    default: 'github-pages'
  directory:
    description: 'Directory to upload'
    required: false
    default: 'public'
  apiToken:
    description: 'Cloudflare API token'
    required: false
  accountId:
    description: 'Cloudflare account ID'
    required: false
  projectName:
    description: 'Cloudflare Pages project name'
    required: false
  gitHubToken:
    description: 'GitHub token'
    required: false
runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v3
    - shell: sh
      run: |
        tar -xvfz github-pages/artifact.tar -C ${{ runner.temp }}/${{ inputs.directory }}
    - uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ inputs.apiToken }}
        accountId: ${{ inputs.accountId }}
        projectName: ${{ inputs.projectName }}
        directory: ${{ runner.temp }}/${{ inputs.directory }}
        gitHubToken: ${{ inputs.gitHubToken }}
        wranglerVersion: '3'
