name: "Publish GitHub Pages artifact"
description: "A composite action that uploads your static assets to a page"
author: "Manuel Schönlaub"
inputs:
  name:
    description: 'Artifact name'
    required: false
runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v3
    - shell: sh
      run: |
        tar -tvf github-pages/artifact.tar
