name: "Publish GitHub Pages artifact"
description: "A composite action that uploads your static assets to a page"
author: "Manuel Schönlaub"
inputs:
  name:
    description: 'Artifact name'
    required: false
    default: 'github-pages/artifact.tar'
runs:
  using: composite
  steps:
    - shell: sh
      run: |
        ls -R 'github-pages'
    - shell: sh
      run: |
        tar xvfz ${{ inputs.name }} ${{ runner.temp }}/pages
    - shell: sh
      run: | 
        ls -R ${{ runner.temp }}/pages
