name: Deploy Hugo site to Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  deployments: write
concurrency:
  group: "pages"
  cancel-in-progress: false
defaults:
  run:
    shell: bash
env:
  BASE_URL: https://schoenlaub.dev/
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.119.0
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Install Dart Sass
        run: sudo snap install dart-sass
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install node dependencies
        run: npm ci
      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL "${{ env.BASE_URL }}"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: public
  deploy:
    environment:
      name: Production
      url: "${{ env.BASE_URL }}"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy page
        uses: "./.github/workflows/actions/upload-pages-artifact"
        with:
          directory: public
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PAGES_PROJECT_NAME }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
